import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Image from 'next/image'

const spiegelSans = localFont({
  variable: '--spiegel-sans',
  src: [
    {
      path: '../../fonts/spiegel/spiegel_tt_regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../../fonts/spiegel/spiegel_tt_semibold.ttf',
      weight: '600',
      style: 'normal'
    },
    {
      path: '../../fonts/spiegel/spiegel_tt_bold.ttf',
      weight: '700',
      style: 'normal'
    },
  ]
})

const beaufortForLol = localFont({
  variable: '--beaufort-for-lol',
  src: [
    {
      path: '../../fonts/beaufortforlol/beaufortforlol_bold.ttf',
      weight: '700',
      style: 'normal'
    },
    {
      path: '../../fonts/beaufortforlol/beaufortforlol_bolditalic.ttf',
      weight: '700',
      style: 'italic'
    },
  ]
})

export const metadata: Metadata = {
  title: 'League of Legends',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${spiegelSans.className} ${beaufortForLol.variable}`}>
        <header className="absolute flex items-center h-32 w-full px-20">
          <Image
            src="/lol.svg"
            alt="League of Legends"
            width={142}
            height={56}
          />
        </header>
        {children}
      </body>
    </html>
  )
}
