import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'

const spiegelSans = localFont({
  variable: '--spiegel-sans',
  src: [
    {
      path: '../../fonts/Spiegel-TTF/Spiegel_TT_Regular.ttf',
      weight: '400',
      style: 'normal'
    },
    {
      path: '../../fonts/Spiegel-TTF/Spiegel_TT_SemiBold.ttf',
      weight: '600',
      style: 'normal'
    },
    {
      path: '../../fonts/Spiegel-TTF/Spiegel_TT_Bold.ttf',
      weight: '700',
      style: 'normal'
    },
  ]
})

const beaufortForLol = localFont({
  variable: '--beaufort-for-lol',
  src: [
    {
      path: '../../fonts/BeaufortForLol-TTF/BeaufortforLOL-Bold.ttf',
      weight: '700',
      style: 'normal'
    },
    {
      path: '../../fonts/BeaufortForLol-TTF/BeaufortforLOL-BoldItalic.ttf',
      weight: '700',
      style: 'italic'
    },
  ]
})

export const metadata: Metadata = {
  title: 'League of Legends',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${spiegelSans.className} ${beaufortForLol.variable}`}>
        {children}
      </body>
    </html>
  )
}
